// ============================================
// GAME LOOP — DO NOT EDIT THIS FILE
// This file orchestrates all the other files.
// Edit player.js, enemies.js, bullets.js,
// collisions.js, and ui.js instead!
// ============================================

function setup() {
  createCanvas(CANVAS_WIDTH, CANVAS_HEIGHT);
  textFont('monospace');
}

function draw() {
  background(COLOR_BACKGROUND);
  frameCounter++;

  if (gameState === 'menu') {
    drawMenu();
  } else if (gameState === 'playing') {
    // Update everything
    updatePlayer();
    updateEnemies();
    updateBullets();
    checkAllCollisions();

    // Draw everything
    drawPlayer();
    drawEnemies();
    drawBullets();
    drawHUD();

    // Increase difficulty over time
    if (frameCounter % DIFFICULTY_INCREASE_INTERVAL === 0) {
      increaseDifficulty();
    }
  } else if (gameState === 'gameover') {
    drawGameOver();
  }
}

function keyPressed() {
  if (gameState === 'menu' && (key === ' ' || keyCode === ENTER)) {
    startGame();
  } else if (gameState === 'gameover' && (key === 'r' || key === 'R')) {
    gameState = 'menu';
  } else if (gameState === 'playing') {
    handlePlayerKeyPress();
  }
}

function mousePressed() {
  if (gameState === 'playing') {
    handlePlayerClick();
  }
}

function startGame() {
  gameState = 'playing';
  score = 0;
  frameCounter = 0;
  resetPlayer();
  resetEnemies();
  resetBullets();
}
